
server:
  port: 8083

spring:
  application:
    name: API-gateway
  cloud:
    gateway:
      routes:
        - id: service1_route
          uri: http://localhost:8081
          predicates:
            - Path=/user-service/**
        - id: service2_route
          uri: http://localhost:8082
          predicates:
            - Path=/supplier/**